//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by 090310_vehicle_speed_measure.rc
//
#define IDD_MY090310_VEHICLE_SPEED_MEASURE_DIALOG 102
#define IDR_MAINFRAME                   128
#define IDC_BUTTON_LOAD_IMG             1001
#define IDC_BUTTON_QUIT                 1002
#define IDC_BUTTON_AFFINE_RECTIFY_ONE_VANISHING_POINT 1004
#define IDC_EDIT_ONE_VANISHING_POINT_SHIFTX 1005
#define IDC_EDIT_ONE_VANISHING_POINT_SHIFTY 1006
#define IDC_BUTTON_GET_FORE_OBJ         1007
#define IDC_EDIT_BINARIZE_THR           1008
#define IDC_EDIT_MOR_CLOSE_STRUCTURE_SIZE 1009
#define IDC_EDIT_MOR_CLOSE_ITERATION    1010
#define IDC_EDIT_N_BLOBS_DETECTED       1011
#define IDC_EDIT_BLOB_AREA_THR          1012
#define IDC_EDIT_N_BLOBS_DETECTED_FOR_TRACKING 1013
#define IDC_BUTTON_VEHICLE_TRACKING     1014
#define IDC_EDIT_MATCHING_WIN_HEIGHT    1015
#define IDC_EDIT_VELOCITY               1016
#define IDC_EDIT_COEFFICIENT_THR        1017
#define IDC_EDIT_SEQ_N_BLOBS_DETECTED   1018
#define IDC_BUTTON_SEQ_BROWSE_IMG       1019
#define IDC_EDIT_ONE_VANISHING_POINT_X  1020
#define IDC_EDIT_SEQ_VANISHING_POINT_X  1021
#define IDC_BUTTON_SEQ_RUN              1022
#define IDC_EDIT_SEQ_BINARIZE_THR       1023
#define IDC_EDIT_SEQ_VANISHING_POINT_Y  1024
#define IDC_EDIT_SEQ_SHIFT_Y            1025
#define IDC_EDIT_SEQ_MOR_CLOSE_STRUCTURE_SIZE 1026
#define IDC_EDIT_SEQ_MOR_CLOSE_ITERATION 1027
#define IDC_EDIT_SEQ_BLOB_AREA_THR      1028
#define IDC_EDIT_SEQ_CROP_FROM_TOP      1029
#define IDC_EDIT_SEQ_CROP_FROM_BOTTOM   1030
#define IDC_EDIT_SEQ_CROP_FROM_LEFT     1031
#define IDC_EDIT_SEQ_CROP_FROM_RIGHT    1032
#define IDC_BUTTON_SEQ_CREATE_BACKGROUND 1033
#define IDC_STATIC_PHM_DX               1034
#define IDC_BUTTON_SEQ_BROWSE_BACKGROUND_IMG 1035
#define IDC_BUTTON_PHM_LOAD_IMG         1036
#define IDC_BUTTON_PHM_COMPENSATE_BACKGROUND 1037
#define IDC_STATIC_PHM_DY               1038
#define IDC_EDIT_PHM_RANGE_DX_FROM      1039
#define IDC_EDIT_PHM_RANGE_DX_TO        1040
#define IDC_EDIT_PHM_RANGE_DY_FROM      1041
#define IDC_EDIT_PHM_RANGE_DY_TO        1042
#define IDC_EDIT_PHM_SMOOTH_WIN_SIZE    1043
#define IDC_EDIT_SEQ_PHM_RANGE_DX_FROM  1044
#define IDC_EDIT_SEQ_PHM_RANGE_DX_TO    1045
#define IDC_EDIT_SEQ_PHM_RANGE_DY_FROM  1046
#define IDC_EDIT_SEQ_PHM_RANGE_DY_TO    1047
#define IDC_EDIT_SEQ_PHM_SMOOTH_WIN_SIZE 1048
#define IDC_STATIC_SEQ_PHM_DX           1049
#define IDC_STATIC_SEQ_PHM_DY           1050
#define IDC_EDIT_SEQ_MATCHING_WIN_HEIGHT 1051
#define IDC_EDIT_SEQ_VELOCITY           1052
#define IDC_EDIT_SEQ_COEFFICIENT_THR    1053
#define IDC_BUTTON_FIND_VANISHING_POINT 1054
#define IDC_BUTTON_FIND_VANISHING_POINT_BROWSE_IMG 1055
#define IDC_EDIT_SEQ_VANISHING_POINT_VOTE_THR 1056
#define IDC_EDIT_SEQ_VANISHING_POINT_LEVEL 1057
#define IDC_BUTTON_EX_COMPARE_PHM_IFD_PHM 1058
#define IDC_STATIC_EX_PHM_IFD_AVG_DX    1059
#define IDC_STATIC_EX_PHM_IFD_MAX_DX    1060
#define IDC_STATIC_EX_PHM_IFD_AVG_DY    1061
#define IDC_STATIC_EX_PHM_IFD_MAX_DY    1062
#define IDC_STATIC_EX_PHM_IFD_AVG_ERROR 1063
#define IDC_BUTTON_EX_COMPARE_PHM_IFD_IFD 1064
#define IDC_BUTTON_SEQ_LOAD_1_BACKGROUND_IMG 1065
#define IDC_RADIO_BLOB_DETECTION_TRACKING 1066
#define IDC_RADIO_PARTICLE_FILTER       1067
#define IDC_EDIT_SEQ_PF_N_PARTICLES     1068
#define IDC_EDIT_SEQ_PF_POSITION_SIGMA  1069
#define IDC_BUTTON_EX_COMPARE_PHM_IFD_NO 1070
#define IDC_STATIC_EX_PHM_IFD_AVG_TIMEDIFF 1071
#define IDC_EDIT_SEQ_PF_VELOCITY_SIGMA  1072
#define IDC_EDIT_SEQ_PF_PARTICLE_WIDTH  1073
#define IDC_EDIT_SEQ_PF_PARTICLE_HEIGHT 1074
#define IDC_STATIC_PROCESSING_TIME      1075
#define IDC_BUTTON_EX_CONVERT_RGB_TO_GRAY 1076
#define IDC_BUTTON_EX_BATCH_RENAME      1077
#define IDC_BUTTON_EX_COMBINE_M2D_RESULTS 1078
#define IDC_STATIC_PHM_ERROR            1079
#define IDC_EDIT_ONE_VANISHING_POINT_SHIFTY2 1080
#define IDC_EDIT_ONE_VANISHING_POINT_Y  1080

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1076
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
